name: ci_server

on:
  push:
    branches:
      - main
      - staging
      - develop

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push server
        uses: docker/build-push-action@v6
        with:
          push: true
          file: ./containers/app/server/Dockerfile.prod
          tags: vanheemstrasystems/prompt-management-server:latest
      - name: Update Docker Hub Description for Server
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: vanheemstrasystems/prompt-management-server
          readme-filepath: ./containers/app/server/DESCRIPTION.md        
        
  # deploy:
  #   runs-on: ubuntu-latest
  #   steps:

  #     - name: Install FTL CLI
  #       run: |
  #         wget https://github.com/yarlson/ftl/releases/latest/download/ftl-linux-amd64
  #         chmod +x ftl-linux-amd64
  #         sudo mv ftl-linux-amd64 /usr/local/bin/ftl

  #     - name: Determine Environment
  #       id: set-env
  #       run: |
  #         if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
  #           echo "environment=production" >> $GITHUB_OUTPUT
  #         elif [[ "${{ github.ref }}" == "refs/heads/staging" ]]; then
  #           echo "environment=staging" >> $GITHUB_OUTPUT
  #         else
  #           echo "environment=development" >> $GITHUB_OUTPUT
  #         fi
  
  #     - name: Configure Hetzner Credentials
  #       run: |
  #         echo "${{ secrets.HETZNER_API_TOKEN }}" | ftl auth login
  
  #     - name: Deploy with FTL
  #       run: |
  #         chmod +x .ftl/deploy.sh
  #         .ftl/deploy.sh ${{ steps.set-env.outputs.environment }}

  #     - name: Health Check
  #       run: |
  #         sleep 60
  #         curl https://prompt-management-server-${{ steps.set-env.outputs.environment }}.yourdomain.com/health
